server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: ${PDMYDB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  privateKey: classpath:pkcs8.key
  publicKey: public-key.pem

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka